# Generated by Django 5.2.8 on 2026-02-09 06:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=10)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('is_verified', models.BooleanField(default=False)),
                ('shop_logo', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
