# Generated by Django 5.2.8 on 2026-02-09 07:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localshop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='localshop',
            name='shop_logo',
            field=models.ImageField(blank=True, null=True, upload_to='shops/'),
        ),
    ]
