# Generated by Django 5.2.8 on 2026-02-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ghotki_Ecommerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=20)),
                ('store_location', models.CharField(max_length=20)),
                ('Store_type', models.CharField(max_length=10)),
                ('store_rate', models.IntegerField()),
                ('store_description', models.TextField(max_length=200)),
                ('store_status', models.BooleanField(default=False)),
            ],
        ),
    ]
