# Generated by Django 5.2.8 on 2026-02-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_rent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('stack', models.CharField(max_length=10)),
                ('experience', models.IntegerField()),
            ],
        ),
    ]
