# Generated by Django 5.2.8 on 2026-02-06 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_rent', '0002_salam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salam',
            name='experience',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
