# Generated by Django 5.2.8 on 2026-02-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_rent', '0003_alter_salam_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salam',
            name='experience',
            field=models.IntegerField(),
        ),
    ]
