# Generated by Django 5.2.8 on 2026-02-07 07:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_rent', '0004_alter_salam_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salamoffices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=20)),
                ('office_location', models.CharField(max_length=30)),
                ('office_workers', models.IntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(50)])),
                ('active_offices', models.BooleanField(default=False)),
            ],
        ),
    ]
