# Generated by Django 5.2.8 on 2026-02-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_rent', '0005_salamoffices'),
    ]

    operations = [
        migrations.AddField(
            model_name='salamoffices',
            name='office_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
