# Generated by Django 5.2.8 on 2026-02-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_rent', '0007_alter_salamoffices_office_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salamoffices',
            name='office_image',
            field=models.ImageField(blank=True, null=True, upload_to='offices/'),
        ),
    ]
