# Generated by Django 5.2.8 on 2026-02-08 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_rent', '0008_alter_salamoffices_office_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=10)),
                ('rating', models.IntegerField(verbose_name=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('is_open', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurants/')),
            ],
        ),
    ]
