# Generated by Django 5.2.8 on 2026-02-08 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_rent', '0009_restaurantprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantprofile',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
